baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ozum's Recipes"
theme = "ezhil"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-139766367-1"

[params]
	subtitle = "Collect and created recipes (mostly vegetarian)"
	# Number of posts to show in recent posts list.
	recentPostsCount = 10
	# Content types which are excluded from recent posts and archive page.
	excludedTypes = ["page"]
	disableDisqusTypes = ["page"]
	featherIconsCDN = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/nazliozum"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/nazliozum"

[taxonomies]
   tag = "tags"
